packages:
  - '.'
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare'
  - astro
  - miniflare
  - wrangler
  - '@types/node@26.5.0'
  - marked@18.0.12
