/// <reference path="../.astro/types.d.ts" />

// Vite raw imports
declare module '*.sql?raw' {
  const content: string;
  export default content;
}

// Cloudflare Workers environment bindings
// In Astro 6 + @astrojs/cloudflare v13, bindings are accessed via
// `import { env } from 'cloudflare:workers'` instead of `locals.runtime.env`
interface D1PreparedStatement {
  first<T = unknown>(): Promise<T | null>;
}

interface D1Database {
  prepare(query: string): D1PreparedStatement;
  batch<T = unknown>(statements: D1PreparedStatement[]): Promise<T[]>;
}

interface R2HTTPMetadata {
  contentType?: string;
  contentDisposition?: string;
}

interface R2ObjectBody {
  body: ReadableStream;
  httpEtag: string;
  httpMetadata?: R2HTTPMetadata;
}

interface R2Bucket {
  put(
    key: string,
    value: ArrayBuffer,
    options?: { httpMetadata?: R2HTTPMetadata },
  ): Promise<unknown>;
  get(key: string): Promise<R2ObjectBody | null>;
  delete(key: string): Promise<void>;
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface CacheStorage {
  readonly default: Cache;
}

interface CloudflareEnv {
  DB: D1Database;
  BUCKET: R2Bucket;
}

// Module declaration for cloudflare:workers env typing
declare module 'cloudflare:workers' {
  const env: CloudflareEnv;
  export { env };
}

// Virtual module: theme template components (generated by theme-loader integration)
declare module 'virtual:theme-templates' {
  import type { ThemeTemplateMap } from '@/lib/theme-props';
  export const themeTemplates: Record<string, Partial<ThemeTemplateMap>>;
}

declare namespace App {
  interface Locals {
    // Execution context (replaces locals.runtime.ctx)
    cfContext?: ExecutionContext;
  }
}
