/// <reference path="../.astro/types.d.ts" />

// Vite raw imports
declare module '*.sql?raw' {
  const content: string;
  export default content;
}

// Cloudflare Workers environment bindings
// In Astro 6 + @astrojs/cloudflare v13, bindings are accessed via
// `import { env } from 'cloudflare:workers'` instead of `locals.runtime.env`
interface CloudflareEnv {
  DB: D1Database;
  BUCKET: R2Bucket;
}

// Module declaration for cloudflare:workers env typing
declare module 'cloudflare:workers' {
  const env: CloudflareEnv;
  export { env };
}

// Virtual module: theme template components (generated by theme-loader integration)
declare module 'virtual:theme-templates' {
  import type { ThemeTemplateMap } from '@/lib/theme-props';
  export const themeTemplates: Record<string, Partial<ThemeTemplateMap>>;
}

declare namespace App {
  interface Locals {
    // Execution context (replaces locals.runtime.ctx)
    cfContext?: ExecutionContext;
  }
}
